export const JSON_SRD = 
[
  ' ./5e-SRD-Ability-Scores.json',
  './5e-SRD-Alignments.json',
  './5e-SRD-Backgrounds.json',
  './5e-SRD-Classes.json',
  './5e-SRD-Conditions.json',
  './5e-SRD-Damage-Types.json',
  './5e-SRD-Equipment-Categories.json',
  './5e-SRD-Equipment.json',
  './5e-SRD-Feats.json',
  './5e-SRD-Features.json',
  './5e-SRD-Languages.json',
  './5e-SRD-Levels.json',
  './5e-SRD-Magic-Items.json',
  './5e-SRD-Magic-Schools.json',
  './5e-SRD-Monsters.json',
  './5e-SRD-Proficiencies.json',
  './5e-SRD-Races.json',
  './5e-SRD-Rule-Sections.json',
  './5e-SRD-Rules.json',
  './5e-SRD-Skills.json',
  './5e-SRD-Spells.json',
  './5e-SRD-Subclasses.json',
  './5e-SRD-Subraces.json',
  './5e-SRD-Traits.json',
  './5e-SRD-Weapon-Properties.json'
]